name: pigma
description: A new Flutter project.

publish_to: "none"

version: 2.1.1+16

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cloud_firestore: 5.4.4
  collection: 1.18.0
  connectivity_plus: ^6.0.5
  equatable: 2.0.5
  flutter_animate: ^4.5.0
  flutter_plugin_android_lifecycle: ^2.0.21
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^7.1.1
  google_fonts: ^6.2.1
  intl: any
  json_path: ^0.7.4
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  mask_text_input_formatter: ^2.9.0
  #geolocator: ^10.0.1

  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_background_service_ios: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  flutter_mapbox_navigation: ^0.2.2
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  device_info_plus: ^9.1.1
  permission_handler: ^11.0.1

  # Notificações
  flutter_local_notifications: ^16.0.0+1

  # Outras dependências
  rxdart: any
  http: any
  http_parser: any
  firebase_core: any

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^4.0.0
  image: ^4.2.0
  lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/icon/rotasysAppIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
